CC=/usr/bin/gcc
MKDIR=/bin/mkdir

BUILD_DIR=./build

all: init
	${CC} -o ${BUILD_DIR}/Q10035 ./ACM_Q10035_practice.c
	${CC} -o ${BUILD_DIR}/Q100   ./ACM_Q100_practice.c
	${CC} -o ${BUILD_DIR}/Q458   ./ACM_Q458_practice.c
	${CC} -o ${BUILD_DIR}/Q494   ./ACM_Q494_practice.c
	${CC} -o ${BUILD_DIR}/Q488   ./ACM_Q488_practice.c

init:
	${MKDIR} -p ${BUILD_DIR}
